### ISSUE TITLE
Order_by with special characters

### ISSUE THREAD

**Issue by junnykx** [intekhabrizvi/Codeigniter-mongo-library#12]
Hello,
I noticed that using the library native order_by function, the special characters order got wrong. The result was something like this:

- Adamantina
- Altair
- Baurú
- Jaú
- São Carlos
- Vinhedo
- Águas da Prata
- Óleo

But the correct order is:

- Adamantina
- Águas da Prata
- Altair
- Baurú
- Jaú
- Óleo
- São Carlos
- Vinhedo
 
So I've used the following solution for this (PHP 5.3+):
```php
// Old database request
$myArray = $this->mongo_db->order_by(array('city' => 'asc'))->get('cities');

// New database request
$myArray = $this->mongo_db->get('cities');

// Remove order_by function and use this instead
usort($myArray, function($o, $n) {
    $ot = iconv('UTF-8', 'ASCII//TRANSLIT', $o['city']);
    $nt = iconv('UTF-8', 'ASCII//TRANSLIT', $n['city']);
    return strcmp($ot, $nt);
});
```

Well, just sharing a solution for a bug that I believe should be fixed. Cheers!

**Comment by intekhabrizvi** [comment]
Thanks for pointing out the issue but I don't think its a bug. 
As you can see in my codes i am just fetching and returning the records as is without doing any ordering or restructuring.
Can you run your codes on PHP MongoDB native function oi simple PHP script and tell me the output ??

**Comment by junnykx** [comment]
Well, using PHP MongoDB native function:

```php
$m = new MongoClient();
$db = $m->mydb;
$collection = $db->cities;

$cursor = $collection->find(array('city' => array('$ne' => '')))->sort(array('city' => 1));

foreach ($cursor as $document) {
	var_dump($document["city"]);
}
```

Result is the same as using your library. So, it's a MongoDB bug...
But it's a very good improvement for this library. I'll report this on PHP MongoDB User Contributed Notes.

Thank you.

**Comment by intekhabrizvi** [comment]
You are welcome.
