### ISSUE TITLE
affected row

### ISSUE THREAD

**Issue by ajitcse1215** [intekhabrizvi/Codeigniter-mongo-library#15]
i need to count of the affected document after update in mongo db , is there any option to find out

**Comment by intekhabrizvi** [comment]
There is no straight forward way of doing this but you can achieve by using getLastError method
ref this 2 links, 
https://docs.mongodb.com/manual/reference/command/getLastError/#getLastError.n
http://php.net/manual/en/mongodb.lasterror.php
