### ISSUE TITLE
Convert this library to a standalone library.

### ISSUE THREAD

**Issue by chiendv** [intekhabrizvi/Codeigniter-mongo-library#17]
Hi @intekhabrizvi,
I create this issue because I dont see any contact information from your profile.
I love and using your library in my projects. But I working on  many kind of project such as ZF, Slim, etc ... 
May you allow me to copy and convert your library to a standalone library so we can use it in any kinds of php project not just CodeIgniter?
My library will be hosted as a public repository in Github and have a copyright and link to your main repository.
Please give me your opinion.

Thank you!

**Comment by intekhabrizvi** [comment]
Hello,

I love open source and without peoples contribution its not possible hence i have no issue as long as you keep including my work details in your source code.

Thanks
