### ISSUE TITLE
Finding Prev / Next document not working!

### ISSUE THREAD

**Issue by avto** [intekhabrizvi/Codeigniter-mongo-library#22]
`function create_next_link($id) 
  {
        $id = new MongoId($id);
        $this->mongo_db->where(array('status' => 1));
        $this->mongo_db->where_gt('_id',$id);
        $this->mongo_db->order_by(array('_id'=>'DESC'));
        $this->mongo_db->limit(1);
        return $this->mongo_db->get('property');
  }`

Above code not returning correct document! Do you have any ideas ?

**Comment by intekhabrizvi** [comment]
Pls check your codes, there is nothing from Library side. Thanks
