### ISSUE TITLE
Unable to run it

### ISSUE THREAD

**Issue by gopalkandoi** [intekhabrizvi/Codeigniter-mongo-library#27]
I followed the process from this [link](http://intekhabrizvi.github.io/mongodb-library-for-codeigniter.html)
but got an error while running a test code 

> The MongoDB PECL extension has not been installed or enabled

`class Test_mongo extends CI_Controller
{
    public function getData(){
        $result = $this->mongo_db->select('blood_request');
        echo $result;
    }
}`

What could be the issue?

**Comment by intekhabrizvi** [comment]
The error message is self explanatory. Your system didn't have mongo driver
installed. Pls use pecl to install it.

**Comment by gopalkandoi** [comment]
Sorry I forgot to mention.
I already installed the mongo php driver following this [link](http://php.net/manual/en/mongo.installation.php#mongo.installation.windows)

Also, my phpinfo() shows mongodb installed.

**Comment by intekhabrizvi** [comment]
There are two drivers in PECL for mongo.

One is mongo and other is mongodb. it seems you installed the mongodb 
driver while this library support mongo driver only.

**Comment by gopalkandoi** [comment]
Thank you.. Done. I was using php version 7 which doesn't support mongo driver. It supports mongodb driver. Switched to php version 5.6 and got it working.
