### ISSUE TITLE
findOne

### ISSUE THREAD

**Issue by consigliere23** [intekhabrizvi/Codeigniter-mongo-library#3]
Add this funcion

**Comment by consigliere23** [comment]
/**
	* --------------------------------------------------------------------------------
	* // getOne
	* --------------------------------------------------------------------------------
	*
	* Get the documents based upon the passed parameters
	*
	* @usage : $this->mongo_db->getOne('foo');
	*/
	public function getOne($collection = "")
	{			
		if (empty($collection))
		{
			show_error("In order to retrieve documents from MongoDB, a collection name must be passed", 500);
		}
		try{	
			$document = $this->db->{$collection}->findOne($this->wheres, $this->selects);
			// Clear
			$this->_clear();
			if(is_null($document)){
				return false;
			}
			return $document;
		}
		catch (MongoCursorException $e)
		{
			if(isset($this->debug) == TRUE && $this->debug == TRUE)
			{
				show_error("MongoDB query failed: {$e->getMessage()}", 500);
			}
			else
			{
				show_error("MongoDB query failed.", 500);
			}
		}
	}

**Comment by intekhabrizvi** [comment]
Add findOne query support, you can use find_one for the same, i used underscore to maintain the naming conventions, Thanks
