### ISSUE TITLE
Library cannot work with PHP7 or "mongodb" PECL driver?

### ISSUE THREAD

**Issue by reolympia** [intekhabrizvi/Codeigniter-mongo-library#32]
If you load the PECL driver "mongodb" you get the error:

    The MongoDB PECL extension has not been installed or enabled

The error is very deceptive because it really should say "The Mongo PECL" ext isn't found and not the "MongoDB" extension. This is because this git repo only works with the PECL library called "mongo". The "mongo" library is not only deprecated but has a PHP requirement of:

pecl/mongo requires PHP (version >= 5.3.0, version <= 5.99.99)

If it is true that the there is no way to use the current "mongodb" driver and we have to downgrade our PHP to 5.x for this to work, can this be added in big bold letters in the readme? I think a lot of us are wasting a lot of time with this library because instructions are unclear. 

Also, it would be courteous to change this line:

    show_error("The MongoDB PECL extension has not been installed or enabled", 500);

To say this:

    show_error("The Mongo PECL extension has not been installed or enabled", 500);

**Comment by SpaceCorp-Us** [comment]
So what is the Solution ? for PHP7-CodeIgniter3 users ?

**Comment by functure** [comment]
I am also looking for a solution myself. Only available solution was this project for me:
https://github.com/verkhoumov/codeigniter-mongodb-library

 I am not sure this will be adequate but it saves the day.

**Comment by verkhoumov** [comment]
@functure, i almost completed the [wiki](https://github.com/verkhoumov/codeigniter-mongodb-library/wiki) section for all functions and fixed some bugs.

**Comment by SpaceCorp-Us** [comment]
Thank you so much, I truly appreciate your efforts !

In the haste to get going on my project I down-graded to PHP5.6

I will soon be working on the PHP7 project again and look over this
information.

Thanks again !
~ Mav

**Comment by zzpwestlife** [comment]
What's the solution? Got the same error. Need help.

**Comment by agmt5989** [comment]
Thank you, man. You _truly_ saved the day.

**Comment by intekhabrizvi** [comment]
Hey everyone,
Sorry, I was pre-occupied with my other commitments hence i didn't pay much attention to writing the library for PHP7.

Anyway it's live now at https://github.com/intekhabrizvi/codeigniter-mongodb-library

**Comment by maxsteel753** [comment]
Still not working with PHP7 and we get the same error

**Comment by SpaceCorp-Us** [comment]
SOLUTION : Use an API (NodeJS+ExpressJS) and never access MongoDB directly. 

~ Best
