### ISSUE TITLE
Hi Rizvi ! Can i use multi like in your library ?

### ISSUE THREAD

**Issue by encodetype** [intekhabrizvi/Codeigniter-mongo-library#39]
something like this .  ->like('aaa','bbb')->or_like('ccc','ddd')   ..
i'm doest't found in your library . sorry

**Comment by vishaldudhatra** [comment]
@encodetype 
Multi like is not possible in this library.
But if you want multi like operation than add below function in this library (Mongo_db.php).


# MULTI OR LIKE 
    public function multi_or_like($like = array(),$flags = "i") {
	    if(!empty($like)){
            foreach ($like as $key=>$value) {
                $this->wheres['$or'][] = array($key => new MongoRegex("/$value/$flags"));
            }
        }
        return $this;
    }

## MULTIPLE AND LIKE
    public function multi_and_like($like = array(),$flags = "i") {
        if(!empty($like)){
            foreach ($like as $key=>$value) {
                $this->wheres['$and'][] = array($key => new MongoRegex("/$value/$flags"));
            }
        }
        return $this;
    }
