### ISSUE TITLE
explain()

### ISSUE THREAD

**Issue by consigliere23** [intekhabrizvi/Codeigniter-mongo-library#4]
Fatal error: Call to a member function explain() on a non-object in app\libraries\Mongo_db.php on line 1763

**Comment by intekhabrizvi** [comment]
Seems your PECL driver for MongoDB is old i am using [this function](http://php.net/manual/en/mongocursor.explain.php) and its need (PECL mongo >=0.9.2)

**Comment by intekhabrizvi** [comment]
Got it, you were trying to perform find_one, i fixed the bug it will work fine now, just a heads up explain() only work for find() function. Thanks
