### ISSUE TITLE
Join two collection

### ISSUE THREAD

**Issue by rakeshrudrapaul** [intekhabrizvi/Codeigniter-mongo-library#45]
how can i join two collection?

Check my collections bellow : 
**First collection, called books, having the following data:**

{
    "isbn": "12",
    "title": "Some cool book",
    "author": "John Doe"
}
{
    "isbn": "13",
    "title": "Another awesome book",
    "author": "Jane Roe"
}

**And the second collection, called books_selling_data, having the following data:**

{
    "_id": ObjectId("56e31bcf76cdf52e541d9d26"),
    "isbn": "12",
    "copies_sold": 12500
}
{
    "_id": ObjectId("56e31ce076cdf52e541d9d28"),
    "isbn": "13",
    "copies_sold": 720050
}

**Comment by apartamenti** [comment]
Add book_id to books_selling_data then you can show with php any of data about books_selling_data.

**Comment by ragavanrandy** [comment]
use embedded documents instead of join.
