### ISSUE TITLE
Aggregation result exceeds maximum document size

### ISSUE THREAD

**Issue by aasghar551** [intekhabrizvi/Codeigniter-mongo-library#46]
I am getting this error message while getting large records
Message: localhost:27017: aggregation result exceeds maximum document size (16MB) php

After that I have added allowDiskUse and maxTimeMS but its still same error
$collection->aggregate($pipeline, array("allowDiskUse" => true, "maxTimeMS" => 1800000));

**Comment by intekhabrizvi** [comment]
Its a MongoDB limitation nothing from the library. Use $project and $match as much as possible to filter all unnecessary data so that the final could be set inside 16MB limit
