### ISSUE TITLE
aggregate cursor error

### ISSUE THREAD

**Issue by mehmetpolat** [intekhabrizvi/Codeigniter-mongo-library#49]
Hi @intekhabrizvi  I'm using your mongodb library but I have a problem, I get this error when I query on mongoDB. I would be very happy if you help

$ops = array(
array('$lookup'=> array('from'=>'balances', 'localField'=> '_id', 'foreignField'=>"OrderID", 'as'=> "balances"))
);
$orders = $this->mongo_db->aggregate('orders', $ops);
print_r($orders);

**Comment by daravichit** [comment]
![Capture](https://user-images.githubusercontent.com/10150355/54100895-63ae6c00-43f3-11e9-8399-bce23f9a4974.PNG)
Me too
Please help

**Comment by byrnes2014** [comment]
Me too
Please help

**Comment by daravichit** [comment]
I solved it but add 'cursor' in to my aggregate option.
Here is my full query code

    ```
 $this->mongo_db->aggregate(
				'user_infos',[
					[
						'$match' => ['phone' => $PhoneNumber],
					],[
						'$project' => [
							'fullname' => 1, 
							'password'  => 1, 
							'branch_id' => 1
						]
					],[
						'$lookup' => [
						  'from' => 'company_branches', 
						  'localField' => 'branch_id', 
						  'foreignField' => '_id', 
						  'as' => 'branchInfo'
						]
					],[
					'cursor' => [ 'batchSize' => 0 ]
				]
			);
```

**Comment by intekhabrizvi** [comment]
@daravichit Could you pls confirm your MongoDB pecl version ??

**Comment by daravichit** [comment]
> MongoDB pecl version

1.6.0alpha1

**Comment by intekhabrizvi** [comment]
@daravichit you are using the wrong library, you need to use the current version of my library located [here](https://github.com/intekhabrizvi/codeigniter-mongodb-library)
