### ISSUE TITLE
method like invalid in php7

### ISSUE THREAD

**Issue by dongminaug** [intekhabrizvi/Codeigniter-mongo-library#51]
method like error, and MongoRegex is invalid in php7.
then,change
 `$regex = "/$value/$flags";
		$this->wheres[$field] = new MongoRegex($regex);`
to 
 `$this->wheres[$field] = [
            '$regex' => '.*'. $value . '.*',
            '$options' => $flags,
        ];`
and it works well.

**Comment by intekhabrizvi** [comment]
This library is for legacy use only, for current PHP and Mongo, use [this one](https://github.com/intekhabrizvi/codeigniter-mongodb-library)
