### ISSUE TITLE
Working with ObjectID

### ISSUE THREAD

**Issue by nhathiwala** [intekhabrizvi/Codeigniter-mongo-library#7]
How to find documents with ObjectID? When I use following data request:
$this->mongo_db->where(array('_id'=>'ObjectId("570e938b407729003100002a")'))->get('school');
It gives me null response, but data exist with that object id, I tried it on bash.

**Comment by mogita** [comment]
I suppose it should be `'_id' => new MongoId("570e938b407729003100002a")` rather than  `'_id'=>'ObjectId("570e938b407729003100002a")'`. The `_id` is an MongoId object.

**Comment by intekhabrizvi** [comment]
Use it like '_id' => new MongoId("570e938b407729003100002a")
